# Generated by Django 4.2.2 on 2023-06-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clan_Simulator_Browser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='health',
            field=models.IntegerField(default=100),
        ),
    ]
