# Generated by Django 4.2.2 on 2023-06-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clan_Simulator_Browser', '0002_member_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
